services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: sp-gateway
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - DIGITAL_LOG_SERVICE_URL=digitallog-backend:5001
      - REQUEST_BODY_LIMIT=100mb
    depends_on:
      - digitallog-backend

  digitallog-backend:
    build:
      context: ./digitallog_and_notification_backend
      dockerfile: Dockerfile
    container_name: sp-digitallog-backend
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - HTTP_PORT=8080
      - APP_PORT=5001
    volumes:
      - ./uploads:/usr/src/app/uploads
